import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home() {

  const [data, setData] = useState();;
  
  const apiKey = "jMtzg2hyaPCMgH8Q8YU9OxEvYT7snnUNcFasbzIl"
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`
  
  const getTechTransferData = async () => {
    const res = await axios.get(url);
    const info = await res.data;
    console.log(info)
    setData(info);
  }

  useEffect(() => {
    getTechTransferData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <div className={styles.nav}>
          <Link className={styles.navtext} href="/"> <div>Home</div> </Link>
          <Link className={styles.navtext} href="/polychromatic"> <div>Polychromatic</div> </Link>
        </div>

        <h1 className={styles.title}>Technology Transfer</h1>
        <div className={styles.row}>
        {
          data && data.results.map((tech, index) => {
            return (
              <div className={styles.container} key={index}>
                {
                  tech && tech.map((t,ind) => {
                    if(ind === 10) {
                      return (
                        <Image src={t} alt={t} key={ind} width={100} height={100} />
                      )
                    }
                  })
                }
            </div>
            )
          })
        }
        </div>
        
      </main>
    </>
  )
}
